import { AcoesSemanticasEnum } from "../../shared/enum/AcoesSemanticas.enum";

export type TokenMap = {
  _symbol: string;
  tokenCode: number;
  isTerminal: boolean;
  isAcaoSemantica?: boolean;
};

export const TokenMapArray: TokenMap[] = [
  // Terminais (1–47)
  { _symbol: "while", tokenCode: 1, isTerminal: true },
  { _symbol: "void", tokenCode: 2, isTerminal: true },
  { _symbol: "string", tokenCode: 3, isTerminal: true },
  { _symbol: "return", tokenCode: 4, isTerminal: true },
  { _symbol: "numerointeiro", tokenCode: 5, isTerminal: true },
  { _symbol: "numerofloat", tokenCode: 6, isTerminal: true },
  { _symbol: "nomevariavel", tokenCode: 7, isTerminal: true },
  { _symbol: "nomedochar", tokenCode: 8, isTerminal: true },
  { _symbol: "nomedastring", tokenCode: 9, isTerminal: true },
  { _symbol: "main", tokenCode: 10, isTerminal: true },
  { _symbol: "literal", tokenCode: 11, isTerminal: true },
  { _symbol: "integer", tokenCode: 12, isTerminal: true },
  { _symbol: "inicio", tokenCode: 13, isTerminal: true },
  { _symbol: "if", tokenCode: 14, isTerminal: true },
  { _symbol: "î", tokenCode: 15, isTerminal: true },
  { _symbol: "for", tokenCode: 16, isTerminal: true },
  { _symbol: "float", tokenCode: 17, isTerminal: true },
  { _symbol: "fim", tokenCode: 18, isTerminal: true },
  { _symbol: "else", tokenCode: 19, isTerminal: true },
  { _symbol: "do", tokenCode: 20, isTerminal: true },
  { _symbol: "cout", tokenCode: 21, isTerminal: true },
  { _symbol: "cin", tokenCode: 22, isTerminal: true },
  { _symbol: "char", tokenCode: 23, isTerminal: true },
  { _symbol: "callfuncao", tokenCode: 24, isTerminal: true },
  { _symbol: ">>", tokenCode: 25, isTerminal: true },
  { _symbol: ">=", tokenCode: 26, isTerminal: true },
  { _symbol: ">", tokenCode: 27, isTerminal: true },
  { _symbol: "==", tokenCode: 28, isTerminal: true },
  { _symbol: "=", tokenCode: 29, isTerminal: true },
  { _symbol: "<=", tokenCode: 30, isTerminal: true },
  { _symbol: "<<", tokenCode: 31, isTerminal: true },
  { _symbol: "<", tokenCode: 32, isTerminal: true },
  { _symbol: "++", tokenCode: 33, isTerminal: true },
  { _symbol: "+", tokenCode: 34, isTerminal: true },
  { _symbol: "}", tokenCode: 35, isTerminal: true },
  { _symbol: "{", tokenCode: 36, isTerminal: true },
  { _symbol: ";", tokenCode: 37, isTerminal: true },
  { _symbol: ":", tokenCode: 38, isTerminal: true },
  { _symbol: "/", tokenCode: 39, isTerminal: true },
  { _symbol: ",", tokenCode: 40, isTerminal: true },
  { _symbol: "*", tokenCode: 41, isTerminal: true },
  { _symbol: ")", tokenCode: 42, isTerminal: true },
  { _symbol: "(", tokenCode: 43, isTerminal: true },
  { _symbol: "$", tokenCode: 44, isTerminal: true },
  { _symbol: "!=", tokenCode: 45, isTerminal: true },
  { _symbol: "--", tokenCode: 46, isTerminal: true },
  { _symbol: "-", tokenCode: 47, isTerminal: true },

  // Não Terminais (48–79)
  { _symbol: "<BLOCO>", tokenCode: 48, isTerminal: false },
  { _symbol: "<DCLVAR>", tokenCode: 49, isTerminal: false },
  { _symbol: "<DCLFUNC>", tokenCode: 50, isTerminal: false },
  { _symbol: "<CORPO>", tokenCode: 51, isTerminal: false },
  { _symbol: "<REPIDENT>", tokenCode: 52, isTerminal: false },
  { _symbol: "<TIPO>", tokenCode: 53, isTerminal: false },
  { _symbol: "<LDVAR>", tokenCode: 54, isTerminal: false },
  { _symbol: "<REPIDEN>", tokenCode: 55, isTerminal: false },
  { _symbol: "<LID>", tokenCode: 56, isTerminal: false },
  { _symbol: "<TIPO_RETORNO>", tokenCode: 57, isTerminal: false },
  { _symbol: "<DEFPAR>", tokenCode: 58, isTerminal: false },
  { _symbol: "<VALORRETORNO>", tokenCode: 59, isTerminal: false },
  { _symbol: "<PARAM>", tokenCode: 60, isTerminal: false },
  { _symbol: "<LPARAM>", tokenCode: 61, isTerminal: false },
  { _symbol: "<COMANDO>", tokenCode: 62, isTerminal: false },
  { _symbol: "<REPCOMANDO>", tokenCode: 63, isTerminal: false },
  { _symbol: "<EXPRESSAO>", tokenCode: 64, isTerminal: false },
  { _symbol: "<PARAMETROS>", tokenCode: 65, isTerminal: false },
  { _symbol: "<TPARAM>", tokenCode: 66, isTerminal: false },
  { _symbol: "<REPPAR>", tokenCode: 67, isTerminal: false },
  { _symbol: "<COMPARACAO>", tokenCode: 68, isTerminal: false },
  { _symbol: "<ELSEPARTE>", tokenCode: 69, isTerminal: false },
  { _symbol: "<CONTCOMPARACAO>", tokenCode: 70, isTerminal: false },
  { _symbol: "<INCREMENTO>", tokenCode: 71, isTerminal: false },
  { _symbol: "<SEQCOUT>", tokenCode: 72, isTerminal: false },
  { _symbol: "<SEQUENCIA>", tokenCode: 73, isTerminal: false },
  { _symbol: "<EXPSIMP>", tokenCode: 74, isTerminal: false },
  { _symbol: "<REPEXPSIMP>", tokenCode: 75, isTerminal: false },
  { _symbol: "<TERMO>", tokenCode: 76, isTerminal: false },
  { _symbol: "<REPEXP>", tokenCode: 77, isTerminal: false },
  { _symbol: "<FATOR>", tokenCode: 78, isTerminal: false },
  { _symbol: "<REPTERMO>", tokenCode: 79, isTerminal: false },

  //Semanticos
  {
    _symbol: AcoesSemanticasEnum.FIM_DECLARACAO_VARIAVEIS,
    tokenCode: 0,
    isTerminal: false,
    isAcaoSemantica: true,
  },
];
