export type TokenMap = {
  tokenNumber: number;
  isTerminal: boolean;
};

export const TokenMap: TokenMap[] = [
  // Terminais (1–47)
  { tokenNumber: 1, isTerminal: true },
  { tokenNumber: 2, isTerminal: true },
  { tokenNumber: 3, isTerminal: true },
  { tokenNumber: 4, isTerminal: true },
  { tokenNumber: 5, isTerminal: true },
  { tokenNumber: 6, isTerminal: true },
  { tokenNumber: 7, isTerminal: true },
  { tokenNumber: 8, isTerminal: true },
  { tokenNumber: 9, isTerminal: true },
  { tokenNumber: 10, isTerminal: true },
  { tokenNumber: 11, isTerminal: true },
  { tokenNumber: 12, isTerminal: true },
  { tokenNumber: 13, isTerminal: true },
  { tokenNumber: 14, isTerminal: true },
  { tokenNumber: 15, isTerminal: true },
  { tokenNumber: 16, isTerminal: true },
  { tokenNumber: 17, isTerminal: true },
  { tokenNumber: 18, isTerminal: true },
  { tokenNumber: 19, isTerminal: true },
  { tokenNumber: 20, isTerminal: true },
  { tokenNumber: 21, isTerminal: true },
  { tokenNumber: 22, isTerminal: true },
  { tokenNumber: 23, isTerminal: true },
  { tokenNumber: 24, isTerminal: true },
  { tokenNumber: 25, isTerminal: true },
  { tokenNumber: 26, isTerminal: true },
  { tokenNumber: 27, isTerminal: true },
  { tokenNumber: 28, isTerminal: true },
  { tokenNumber: 29, isTerminal: true },
  { tokenNumber: 30, isTerminal: true },
  { tokenNumber: 31, isTerminal: true },
  { tokenNumber: 32, isTerminal: true },
  { tokenNumber: 33, isTerminal: true },
  { tokenNumber: 34, isTerminal: true },
  { tokenNumber: 35, isTerminal: true },
  { tokenNumber: 36, isTerminal: true },
  { tokenNumber: 37, isTerminal: true },
  { tokenNumber: 38, isTerminal: true },
  { tokenNumber: 39, isTerminal: true },
  { tokenNumber: 40, isTerminal: true },
  { tokenNumber: 41, isTerminal: true },
  { tokenNumber: 42, isTerminal: true },
  { tokenNumber: 43, isTerminal: true },
  { tokenNumber: 44, isTerminal: true },
  { tokenNumber: 45, isTerminal: true },
  { tokenNumber: 46, isTerminal: true },
  { tokenNumber: 47, isTerminal: true },

  // Não Terminais (48–79)
  { tokenNumber: 48, isTerminal: false },
  { tokenNumber: 49, isTerminal: false },
  { tokenNumber: 50, isTerminal: false },
  { tokenNumber: 51, isTerminal: false },
  { tokenNumber: 52, isTerminal: false },
  { tokenNumber: 53, isTerminal: false },
  { tokenNumber: 54, isTerminal: false },
  { tokenNumber: 55, isTerminal: false },
  { tokenNumber: 56, isTerminal: false },
  { tokenNumber: 57, isTerminal: false },
  { tokenNumber: 58, isTerminal: false },
  { tokenNumber: 59, isTerminal: false },
  { tokenNumber: 60, isTerminal: false },
  { tokenNumber: 61, isTerminal: false },
  { tokenNumber: 62, isTerminal: false },
  { tokenNumber: 63, isTerminal: false },
  { tokenNumber: 64, isTerminal: false },
  { tokenNumber: 65, isTerminal: false },
  { tokenNumber: 66, isTerminal: false },
  { tokenNumber: 67, isTerminal: false },
  { tokenNumber: 68, isTerminal: false },
  { tokenNumber: 69, isTerminal: false },
  { tokenNumber: 70, isTerminal: false },
  { tokenNumber: 71, isTerminal: false },
  { tokenNumber: 72, isTerminal: false },
  { tokenNumber: 73, isTerminal: false },
  { tokenNumber: 74, isTerminal: false },
  { tokenNumber: 75, isTerminal: false },
  { tokenNumber: 76, isTerminal: false },
  { tokenNumber: 77, isTerminal: false },
  { tokenNumber: 78, isTerminal: false },
  { tokenNumber: 79, isTerminal: false },
];
